apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-xgcl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-xgcl
    app.kubernetes.io/part-of: test-rhtap-4-app
  name: devfile-sample-code-with-quarkus-xgcl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-xgcl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-xgcl
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-4-tenant/test-rhtap-4-app/devfile-sample-code-with-quarkus-xgcl@sha256:b4950175be4f289ccaf82fc956efb968cd3faca4bbf9f4ada8fae899cbf8ac64
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
